import type { Listing, Review } from "./types";

// Placeholder images from picsum (deterministic by seed)
const img = (id: number) => `https://picsum.photos/seed/lokacia${id}/800/600`;

export const listings: Listing[] = [
  {
    id: "1",
    title: "Daylight Studio — Циклорама 6м",
    slug: "daylight-studio-cyclorama-6m",
    description:
      "Просторная фотостудия с белой циклорамой 6 метров, панорамными окнами и естественным светом. Полный комплект студийного оборудования: 4 импульсных источника Profoto, софтбоксы, фоны. Идеально для каталожной съёмки, портретов и видеоконтента. Гримёрная комната, кухня для перерывов.",
    spaceType: "photo_studio",
    activityTypes: ["production"],
    city: "almaty",
    district: "Медеуский",
    address: "ул. Панфилова 78, офис 12",
    lat: 43.238,
    lng: 76.946,
    area: 120,
    capacity: 15,
    ceilingHeight: 4.5,
    pricePerHour: 8000,
    pricePerDay: 50000,
    minHours: 2,
    images: [img(1), img(2), img(3), img(4), img(5)],
    styles: ["modern", "minimalist"],
    amenities: [
      "Циклорама 6м",
      "Profoto оборудование",
      "Естественный свет",
      "Гримёрная",
      "Кухня",
      "Wi-Fi",
      "Парковка",
      "Кондиционер",
    ],
    rules: [
      "Без обуви на циклораме",
      "Уборка включена в стоимость",
      "Не более 15 человек",
    ],
    allows: { alcohol: false, loudMusic: false, pets: false, smoking: false, food: true },
    hostId: "h1",
    hostName: "Алия К.",
    hostAvatar: img(101),
    hostPhone: "+7 777 111 2233",
    rating: 4.9,
    reviewCount: 47,
    instantBook: true,
    superhost: true,
    createdAt: "2025-09-15",
  },
  {
    id: "2",
    title: "Лофт FACTORY — Ивенты до 200 человек",
    slug: "loft-factory-events-200",
    description:
      "Индустриальный лофт площадью 350м² с высокими потолками, кирпичными стенами и панорамными окнами. Два зала: основной на 200 человек и VIP на 40. Профессиональный звук и свет, сцена, проектор. Идеально для корпоративов, свадеб, концертов и презентаций. Своя кухня, бар, терраса.",
    spaceType: "loft",
    activityTypes: ["event", "production"],
    city: "almaty",
    district: "Бостандыкский",
    address: "ул. Тимирязева 42",
    lat: 43.235,
    lng: 76.926,
    area: 350,
    capacity: 200,
    ceilingHeight: 6,
    pricePerHour: 25000,
    pricePerDay: 180000,
    minHours: 4,
    images: [img(10), img(11), img(12), img(13), img(14)],
    styles: ["industrial", "loft"],
    amenities: [
      "Сцена",
      "Профессиональный звук",
      "Проектор",
      "Кухня",
      "Бар",
      "Терраса",
      "Парковка 30 мест",
      "Wi-Fi",
      "Кондиционер",
    ],
    rules: [
      "Окончание мероприятий до 23:00",
      "Залог 100 000 ₸",
      "Уборка включена",
    ],
    allows: { alcohol: true, loudMusic: true, pets: false, smoking: false, food: true },
    hostId: "h2",
    hostName: "Тимур Б.",
    hostAvatar: img(102),
    hostPhone: "+7 701 222 3344",
    rating: 4.8,
    reviewCount: 93,
    instantBook: false,
    superhost: true,
    createdAt: "2025-06-01",
  },
  {
    id: "3",
    title: "Квартира в стиле mid-century для съёмок",
    slug: "apartment-midcentury-filming",
    description:
      "Стильная двухкомнатная квартира 85м² в центре Алматы. Дизайнерский ремонт в стиле mid-century modern: винтажная мебель, тёплые тона, паркет. Большие окна, много света. Популярна среди фотографов и видеографов для lifestyle-контента, интервью и рекламных съёмок.",
    spaceType: "apartment",
    activityTypes: ["production"],
    city: "almaty",
    district: "Алмалинский",
    address: "ул. Кабанбай Батыра 120, кв. 15",
    lat: 43.257,
    lng: 76.948,
    area: 85,
    capacity: 10,
    ceilingHeight: 3,
    pricePerHour: 5000,
    pricePerDay: 35000,
    minHours: 3,
    images: [img(20), img(21), img(22), img(23)],
    styles: ["vintage", "modern"],
    amenities: [
      "Дизайнерская мебель",
      "Естественный свет",
      "Кухня",
      "Wi-Fi",
      "Парковка во дворе",
    ],
    rules: [
      "Без обуви",
      "Не двигать мебель без согласования",
      "Тишина после 21:00",
    ],
    allows: { alcohol: false, loudMusic: false, pets: false, smoking: false, food: true },
    hostId: "h3",
    hostName: "Дана М.",
    hostAvatar: img(103),
    hostPhone: "+7 707 333 4455",
    rating: 4.7,
    reviewCount: 28,
    instantBook: true,
    superhost: false,
    createdAt: "2025-11-20",
  },
  {
    id: "4",
    title: "Sound Stage QAZAQ — Павильон 500м²",
    slug: "sound-stage-qazaq-500",
    description:
      "Профессиональный звуковой павильон для кино и видеопродакшн. 500м², высота потолков 8м, полная звукоизоляция. Электрическая мощность 200 кВт, грузовой доступ для декораций. Гримёрные, комната отдыха, техническая зона. Рядом с Kazakhfilm Studios.",
    spaceType: "sound_stage",
    activityTypes: ["production"],
    city: "almaty",
    district: "Наурызбайский",
    address: "Казахфильм, павильон 4",
    lat: 43.208,
    lng: 76.882,
    area: 500,
    capacity: 50,
    ceilingHeight: 8,
    pricePerHour: 50000,
    pricePerDay: 350000,
    minHours: 8,
    images: [img(30), img(31), img(32), img(33), img(34)],
    styles: ["industrial"],
    amenities: [
      "Звукоизоляция",
      "200 кВт мощность",
      "Грузовой доступ",
      "Гримёрные",
      "Комната отдыха",
      "Парковка",
      "Wi-Fi",
    ],
    rules: [
      "Минимум 8 часов",
      "Техник-консультант включён",
      "Бронирование за 7 дней",
    ],
    allows: { alcohol: false, loudMusic: true, pets: false, smoking: false, food: true },
    hostId: "h4",
    hostName: "Арман Т.",
    hostAvatar: img(104),
    hostPhone: "+7 700 444 5566",
    rating: 5.0,
    reviewCount: 12,
    instantBook: false,
    superhost: false,
    createdAt: "2026-01-10",
  },
  {
    id: "5",
    title: "Юрта «Номад» — Этно-площадка для съёмок",
    slug: "yurt-nomad-ethno",
    description:
      "Аутентичная казахская юрта с полным традиционным убранством: сырмақ, тұскиіз, текемет, дастархан. Площадь юрты 60м², установлена на территории частного подворья с видом на горы. Идеально для этно-съёмок, документального кино, свадебных фотосессий и национальных мероприятий.",
    spaceType: "yurt",
    activityTypes: ["production", "event"],
    city: "almaty",
    district: "Медеуский",
    address: "пос. Тау-Самалы, ул. Жибек Жолы 5",
    lat: 43.19,
    lng: 76.97,
    area: 60,
    capacity: 30,
    pricePerHour: 15000,
    pricePerDay: 100000,
    minHours: 3,
    images: [img(40), img(41), img(42), img(43)],
    styles: ["ethno", "rustic"],
    amenities: [
      "Традиционное убранство",
      "Вид на горы",
      "Дастархан",
      "Территория 500м²",
      "Парковка",
      "Генератор",
    ],
    rules: [
      "Бережное отношение к убранству",
      "Обувь при входе снимать",
      "Согласование декора заранее",
    ],
    allows: { alcohol: true, loudMusic: false, pets: false, smoking: false, food: true },
    hostId: "h5",
    hostName: "Бахыт Н.",
    hostAvatar: img(105),
    hostPhone: "+7 708 555 6677",
    rating: 4.9,
    reviewCount: 35,
    instantBook: false,
    superhost: true,
    createdAt: "2025-08-01",
  },
  {
    id: "6",
    title: "Ресторан «Астау» — Банкеты и тои",
    slug: "restaurant-astau-banquets",
    description:
      "Элегантный ресторан с двумя залами: основной на 150 человек и VIP на 30. Современный интерьер с элементами казахского орнамента. Собственная кухня (казахская, европейская), профессиональный звук и свет, танцпол, сцена для живой музыки. Парковка на 50 машин.",
    spaceType: "restaurant",
    activityTypes: ["event"],
    city: "almaty",
    district: "Ауэзовский",
    address: "пр. Абая 150",
    lat: 43.24,
    lng: 76.89,
    area: 400,
    capacity: 150,
    ceilingHeight: 4,
    pricePerHour: 35000,
    pricePerDay: 250000,
    minHours: 5,
    images: [img(50), img(51), img(52), img(53), img(54)],
    styles: ["classic", "modern"],
    amenities: [
      "Кухня",
      "Сцена",
      "Танцпол",
      "Профессиональный звук",
      "Проектор",
      "Парковка 50 мест",
      "Wi-Fi",
      "Кондиционер",
    ],
    rules: [
      "Окончание до 00:00",
      "Своё спиртное запрещено",
      "Залог 200 000 ₸",
    ],
    allows: { alcohol: true, loudMusic: true, pets: false, smoking: false, food: true },
    hostId: "h6",
    hostName: "Ерлан С.",
    hostAvatar: img(106),
    hostPhone: "+7 702 666 7788",
    rating: 4.6,
    reviewCount: 64,
    instantBook: false,
    superhost: false,
    createdAt: "2025-07-15",
  },
  {
    id: "7",
    title: "Горное шале «Көкжайлау» — Вид на город",
    slug: "mountain-chalet-kokzhailau",
    description:
      "Уютное шале на высоте 1400м с панорамным видом на Алматы. 180м², 3 спальни, камин, терраса 50м². Идеально для камерных мероприятий, retreats, фотосессий на фоне гор. Зимой — рядом горнолыжный курорт, летом — hiking-тропы.",
    spaceType: "chalet",
    activityTypes: ["production", "event", "leisure"],
    city: "almaty",
    district: "Медеуский",
    address: "Горная резиденция «Көкжайлау», дом 7",
    lat: 43.16,
    lng: 77.06,
    area: 180,
    capacity: 25,
    ceilingHeight: 3.5,
    pricePerHour: 20000,
    pricePerDay: 150000,
    minHours: 4,
    images: [img(60), img(61), img(62), img(63), img(64)],
    styles: ["rustic", "modern"],
    amenities: [
      "Панорамный вид",
      "Камин",
      "Терраса 50м²",
      "3 спальни",
      "Кухня",
      "Парковка",
      "Wi-Fi",
      "Генератор",
    ],
    rules: [
      "Тишина после 22:00",
      "Запрет на фейерверки",
      "Уборка за доп. плату 15 000 ₸",
    ],
    allows: { alcohol: true, loudMusic: false, pets: true, smoking: false, food: true },
    hostId: "h7",
    hostName: "Нурлан К.",
    hostAvatar: img(107),
    hostPhone: "+7 705 777 8899",
    rating: 4.8,
    reviewCount: 19,
    instantBook: false,
    superhost: false,
    createdAt: "2025-12-01",
  },
  {
    id: "8",
    title: "Коворкинг HUB — Переговорные от 4 до 20 чел",
    slug: "coworking-hub-meeting-rooms",
    description:
      "Современный коворкинг в центре Астаны. 5 переговорных комнат вместимостью от 4 до 20 человек. Каждая оборудована ТВ, маркерными досками, видеоконференцией. Лобби с кофе-машиной. Удобно для интервью, воркшопов, тренингов и презентаций.",
    spaceType: "coworking",
    activityTypes: ["meeting", "production"],
    city: "astana",
    district: "Есильский",
    address: "пр. Мәңгілік Ел 35",
    lat: 51.128,
    lng: 71.43,
    area: 45,
    capacity: 20,
    ceilingHeight: 3,
    pricePerHour: 6000,
    minHours: 1,
    images: [img(70), img(71), img(72), img(73)],
    styles: ["modern", "minimalist"],
    amenities: [
      "ТВ / проектор",
      "Маркерные доски",
      "Видеоконференция",
      "Кофе-машина",
      "Wi-Fi",
      "Парковка",
      "Кондиционер",
    ],
    rules: ["Без еды в переговорных", "Бронирование от 1 часа"],
    allows: { alcohol: false, loudMusic: false, pets: false, smoking: false, food: false },
    hostId: "h8",
    hostName: "Айнур Ж.",
    hostAvatar: img(108),
    hostPhone: "+7 778 888 9900",
    rating: 4.5,
    reviewCount: 41,
    instantBook: true,
    superhost: false,
    createdAt: "2025-10-05",
  },
  {
    id: "9",
    title: "Black Box Studio — Фото и видео",
    slug: "black-box-studio",
    description:
      "Чёрная студия 90м² с полной звукоизоляцией. Идеально для предметной съёмки, видеоклипов, подкастов. Оборудование: Godox AD600, LED-панели, зелёный экран, телеприсяжка. Гримёрная, костюмерная.",
    spaceType: "video_studio",
    activityTypes: ["production"],
    city: "almaty",
    district: "Бостандыкский",
    address: "ул. Розыбакиева 247",
    lat: 43.228,
    lng: 76.929,
    area: 90,
    capacity: 12,
    ceilingHeight: 4,
    pricePerHour: 10000,
    pricePerDay: 65000,
    minHours: 2,
    images: [img(80), img(81), img(82), img(83)],
    styles: ["modern", "industrial"],
    amenities: [
      "Звукоизоляция",
      "Зелёный экран",
      "LED-панели",
      "Godox оборудование",
      "Гримёрная",
      "Костюмерная",
      "Wi-Fi",
      "Кондиционер",
    ],
    rules: [
      "Обувь снимать",
      "Своё оборудование — по согласованию",
      "Не более 12 человек",
    ],
    allows: { alcohol: false, loudMusic: true, pets: false, smoking: false, food: false },
    hostId: "h9",
    hostName: "Руслан А.",
    hostAvatar: img(109),
    hostPhone: "+7 771 999 0011",
    rating: 4.9,
    reviewCount: 56,
    instantBook: true,
    superhost: true,
    createdAt: "2025-05-20",
  },
  {
    id: "10",
    title: "Терраса «Высота» — Open-air ивенты",
    slug: "terrasa-vysota-openair",
    description:
      "Открытая терраса на крыше ТЦ с видом на горы Алатау. 250м² под открытым небом + крытая зона 80м². Подходит для летних вечеринок, презентаций, свадебных церемоний, фотосессий. Собственный бар, DJ-пульт, освещение.",
    spaceType: "outdoor",
    activityTypes: ["event", "production", "leisure"],
    city: "almaty",
    district: "Медеуский",
    address: "пр. Достык 89, крыша",
    lat: 43.243,
    lng: 76.955,
    area: 330,
    capacity: 120,
    pricePerHour: 30000,
    pricePerDay: 200000,
    minHours: 3,
    images: [img(90), img(91), img(92), img(93), img(94)],
    styles: ["modern"],
    amenities: [
      "Вид на горы",
      "Бар",
      "DJ-пульт",
      "Освещение",
      "Крытая зона 80м²",
      "Парковка",
      "Wi-Fi",
    ],
    rules: [
      "Сезон: май-сентябрь",
      "Окончание до 23:00",
      "Залог 150 000 ₸",
    ],
    allows: { alcohol: true, loudMusic: true, pets: false, smoking: true, food: true },
    hostId: "h10",
    hostName: "Мадина Р.",
    hostAvatar: img(110),
    hostPhone: "+7 700 111 2233",
    rating: 4.7,
    reviewCount: 38,
    instantBook: false,
    superhost: false,
    createdAt: "2025-04-10",
  },
];

export const reviews: Review[] = [
  { id: "r1", listingId: "1", authorName: "Марат К.", authorAvatar: img(201), rating: 5, text: "Отличная студия! Свет потрясающий, оборудование в идеальном состоянии. Алия очень отзывчивый хост.", createdAt: "2026-03-10" },
  { id: "r2", listingId: "1", authorName: "Света П.", authorAvatar: img(202), rating: 5, text: "Снимала каталог одежды — циклорама идеальная, пространства хватает. Приду ещё!", createdAt: "2026-02-25" },
  { id: "r3", listingId: "1", authorName: "Ержан Т.", authorAvatar: img(203), rating: 4, text: "Хорошая студия, всё как в описании. Единственное — парковка ограничена.", createdAt: "2026-01-14" },
  { id: "r4", listingId: "2", authorName: "Айгерим Б.", authorAvatar: img(204), rating: 5, text: "Провели корпоратив на 150 человек — всё прошло идеально. Звук и свет на высшем уровне.", createdAt: "2026-03-20" },
  { id: "r5", listingId: "2", authorName: "Данияр М.", authorAvatar: img(205), rating: 5, text: "Снимали клип в лофте — атмосфера невероятная. Тимур помог с организацией.", createdAt: "2026-02-05" },
  { id: "r6", listingId: "5", authorName: "Карина Л.", authorAvatar: img(206), rating: 5, text: "Юрта просто великолепная! Свадебная фотосессия получилась волшебной.", createdAt: "2026-03-01" },
];

export function getListingBySlug(slug: string): Listing | undefined {
  return listings.find((l) => l.slug === slug);
}

export function getReviewsByListingId(listingId: string): Review[] {
  return reviews.filter((r) => r.listingId === listingId);
}
